// =============================================================================
// tb_axi_mem_slave.sv - V0..V5 for boot_rom.sv (-GIS_ROM=1) and sram_controller.sv (-GIS_ROM=0)
//
// Reference model: a byte-accurate word array in the TB.
//   * ROM  : contents come from rom_test.hex (generated by the regression runner from
//            the same formula as rom_word()); every write is drained and answered SLVERR,
//            contents never change.
//   * SRAM : writes apply byte strobes per beat (INCR bursts); a beat outside the array
//            is dropped and the burst response becomes SLVERR.
//   * reads beyond the array return data 0 with rresp=SLVERR (both).
// AXI master BFM randomises RREADY / BREADY / AW-W presentation delays.
// Assertions: response stability under back-pressure, single B per write, RLAST only on
//   the final beat, R/B mutually exclusive, SRAM never ready on AR and AW together.
// =============================================================================
module tb_axi_mem_slave import rv32im_pkg::*;;
  `include "tb_common.svh"

  parameter bit IS_ROM = 1'b1;
  localparam int WORDS = 64;
  // real region base: SRAM lives at 0x1000_0000 (this exposed RTL bug #3); ROM at 0
  localparam logic [31:0] BASE = IS_ROM ? 32'h0000_0000 : 32'h1000_0000;

  logic clk = 0, rst_n = 0;
  axi_req_t s_req;  axi_rsp_t s_rsp;

  always #5 clk = ~clk;
  always @(posedge clk) cyc++;

  generate
    if (IS_ROM) begin : g_rom
      boot_rom #(.WORDS(WORDS), .INIT_FILE("rom_test.hex")) dut (.clk(clk), .rst_n(rst_n), .s_req(s_req), .s_rsp(s_rsp));
    end else begin : g_sram
      sram_controller #(.WORDS(WORDS)) dut (.clk(clk), .rst_n(rst_n), .s_req(s_req), .s_rsp(s_rsp));
    end
  endgenerate

  // ---- reference memory ---------------------------------------------------------
  logic [31:0] rm [WORDS];
  function automatic logic [31:0] rom_word(input int i);       // same formula as the generator
    return 32'h1000_0000 + 32'(i) * 32'h0000_0111 ^ 32'hA5A5_0000;
  endfunction

  // ---- V3 assertions --------------------------------------------------------------------
  ap_r_stable: assert property (@(posedge clk) disable iff (!rst_n)
                  (s_rsp.rvalid && !s_req.rready) |=> (s_rsp.rvalid && $stable(s_rsp.rdata) && $stable(s_rsp.rresp) && $stable(s_rsp.rlast)));
  ap_b_stable: assert property (@(posedge clk) disable iff (!rst_n)
                  (s_rsp.bvalid && !s_req.bready) |=> (s_rsp.bvalid && $stable(s_rsp.bresp)));
  ap_no_both:  assert property (@(posedge clk) disable iff (!rst_n) !(s_rsp.rvalid && s_rsp.bvalid));
  ap_sram_excl: assert property (@(posedge clk) disable iff (!rst_n) (!IS_ROM) |-> !(s_rsp.arready && s_rsp.awready));
  ap_sram_busy: assert property (@(posedge clk) disable iff (!rst_n)
                  (!IS_ROM && (s_rsp.rvalid || s_rsp.bvalid || s_rsp.wready)) |-> (!s_rsp.arready && !s_rsp.awready));
  ap_rom_wresp: assert property (@(posedge clk) disable iff (!rst_n)
                  (IS_ROM && s_rsp.bvalid) |-> (s_rsp.bresp == AXI_RESP_SLVERR));

  // ---- master BFM: reads --------------------------------------------------------------------
  task automatic rd(input logic [31:0] a, input logic [7:0] len, input int rr_pct, input bit is_rand);
    int beats = 0, guard = 0, bad_d = 0, bad_r = 0, bad_l = 0;
    int idx;
    logic [31:0] exp_d;
    bit          exp_e;
    @(negedge clk);
    s_req.arvalid = 1; s_req.araddr = a | BASE; s_req.arlen = len; s_req.arsize = 3'b010; s_req.arburst = 2'b01;
    #1;
    while (!s_rsp.arready && guard < 500) begin @(negedge clk); #1; guard++; end
    @(posedge clk); @(negedge clk);
    s_req.arvalid = 0;
    guard = 0;
    while (beats <= int'(len) && guard < 1500) begin
      s_req.rready = ($urandom_range(0, 99) < rr_pct);
      #1;
      if (s_rsp.rvalid && s_req.rready) begin
        idx   = int'(((a & 32'h0FFF_FFFF) >> 2) + beats);
        exp_e = (idx >= WORDS);
        exp_d = exp_e ? 32'd0 : rm[idx];
        if (s_rsp.rdata !== exp_d) bad_d++;
        if (s_rsp.rresp !== (exp_e ? AXI_RESP_SLVERR : AXI_RESP_OKAY)) bad_r++;
        if (s_rsp.rlast !== (beats == int'(len))) bad_l++;
        if (exp_e) cov_hit(3);
        beats++;
      end
      @(negedge clk); guard++;
    end
    s_req.rready = 0;
    if (guard >= 1500) chk("read_TIMEOUT", 1, 0);
    repeat (2) @(negedge clk);
    if (is_rand) begin
      rchk("rd_beats", 64'(len) + 1, 64'(beats)); rchk("rd_data", 0, 64'(bad_d));
      rchk("rd_resp", 0, 64'(bad_r)); rchk("rd_last", 0, 64'(bad_l));
    end else begin
      chk($sformatf("rd_beats a=%08h len=%0d", a, len), 64'(len) + 1, 64'(beats));
      chk($sformatf("rd_data a=%08h", a), 0, 64'(bad_d)); chk("rd_resp", 0, 64'(bad_r)); chk("rd_last", 0, 64'(bad_l));
    end
    cov_hit(0); if (len != 0) cov_hit(1); if (rr_pct < 100) cov_hit(2);
    if ((a >> 2) + len >= WORDS && (a >> 2) < WORDS) cov_hit(4);     // burst crossing the end
  endtask

  // ---- master BFM: writes -----------------------------------------------------------------------
  logic [31:0] wd [16];  logic [3:0] ws [16];
  task automatic wr(input logic [31:0] a, input int nb, input int b_pct, input int w_gap_pct, input int aw_dly, input bit is_rand);
    int guard = 0, sent = 0, bresp_bad = 0;
    bit aw_done = 0, got_b = 0, bad_any = 0, aw_hs;
    logic [1:0] exp_resp, got_resp;
    // expected reference update + response
    for (int i = 0; i < nb; i++) begin
      int idx = int'(((a & 32'h0FFF_FFFF) >> 2) + i);
      if (idx >= WORDS) bad_any = 1;
      else if (!IS_ROM)
        for (int b = 0; b < 4; b++) if (ws[i][b]) rm[idx][8*b +: 8] = wd[i][8*b +: 8];
    end
    exp_resp = (IS_ROM || bad_any) ? AXI_RESP_SLVERR : AXI_RESP_OKAY;
    @(negedge clk);
    repeat (aw_dly) @(negedge clk);
    s_req.awvalid = 1; s_req.awaddr = a | BASE; s_req.awlen = 8'(nb - 1); s_req.awsize = 3'b010; s_req.awburst = 2'b01;
    while (!aw_done && guard < 500) begin
      #1; aw_hs = s_rsp.awready;
      @(negedge clk); if (aw_hs) begin aw_done = 1; s_req.awvalid = 0; end guard++;
    end
    guard = 0;
    while (sent < nb && guard < 2000) begin
      if (!s_req.wvalid && ($urandom_range(0, 99) >= w_gap_pct)) begin
        s_req.wvalid = 1; s_req.wdata = wd[sent]; s_req.wstrb = ws[sent]; s_req.wlast = (sent == nb - 1);
      end
      #1;
      if (s_req.wvalid && s_rsp.wready) begin @(posedge clk); @(negedge clk); s_req.wvalid = 0; s_req.wlast = 0; sent++; end
      else @(negedge clk);
      guard++;
    end
    guard = 0;
    while (!got_b && guard < 1500) begin
      s_req.bready = ($urandom_range(0, 99) < b_pct);
      #1;
      if (s_rsp.bvalid && s_req.bready) begin got_b = 1; got_resp = s_rsp.bresp; end
      @(negedge clk); guard++;
    end
    s_req.bready = 0;
    if (!got_b) chk("write_TIMEOUT", 1, 0);
    repeat (2) @(negedge clk);
    if (is_rand) begin
      rchk("wr_all_beats", 64'(nb), 64'(sent)); rchk("wr_bresp", {62'd0, exp_resp}, {62'd0, got_resp});
      rchk("wr_single_b", 0, {63'd0, s_rsp.bvalid});
    end else begin
      chk($sformatf("wr_all_beats a=%08h nb=%0d", a, nb), 64'(nb), 64'(sent));
      chk($sformatf("wr_bresp a=%08h", a), {62'd0, exp_resp}, {62'd0, got_resp});
      chk("wr_single_b", 0, {63'd0, s_rsp.bvalid});
    end
    cov_hit(5); if (nb > 1) cov_hit(6); if (bad_any) cov_hit(7);
    for (int i = 0; i < nb; i++) if (ws[i] != 4'hF && ws[i] != 4'h0) cov_hit(8);
    if (b_pct < 100) cov_hit(9);
    if (w_gap_pct > 0) cov_hit(10);
  endtask

  task automatic wr1(input logic [31:0] a, input logic [31:0] d, input logic [3:0] s, input bit is_rand = 0);
    wd[0] = d; ws[0] = s; wr(a, 1, 100, 0, 0, is_rand);
  endtask

  initial begin
    tb_init(IS_ROM ? "boot_rom" : "sram_controller");
    cov_def(0,"read_single"); cov_def(1,"read_burst"); cov_def(2,"rready_backpressure");
    cov_def(3,"read_out_of_range_beat"); cov_def(4,"burst_crosses_end"); cov_def(5,"write");
    cov_def(6,"write_burst"); cov_def(7,"write_out_of_range"); cov_def(8,"partial_strobe");
    cov_def(9,"bready_backpressure"); cov_def(10,"w_gaps");
    s_req = AXI_REQ_IDLE;
    if (IS_ROM) for (int i = 0; i < WORDS; i++) rm[i] = rom_word(i);
    else        for (int i = 0; i < WORDS; i++) rm[i] = 32'd0;      // sim zero-fill documented in the RTL
    repeat (3) @(negedge clk);
    rst_n = 1; @(negedge clk);

    // ---- V1: read every word individually --------------------------------------------------------
    for (int i = 0; i < WORDS; i++) rd(32'(i * 4), 0, 100, 0);
    // ---- V1: bursts, boundaries, out-of-range ---------------------------------------------------------
    rd(32'h0000_0000, 8'd3, 100, 0);
    rd(32'h0000_0020, 8'd7, 100, 0);
    rd(32'h0000_0040, 8'd15, 100, 0);
    rd(32'(4 * (WORDS - 1)), 8'd0, 100, 0);              // last legal word
    rd(32'(4 * WORDS), 8'd0, 100, 0);                     // first illegal word -> SLVERR, data 0
    rd(32'(4 * (WORDS - 2)), 8'd3, 100, 0);               // burst running off the end
    rd(32'(4 * (WORDS + 100)), 8'd1, 100, 0);
    rd(32'h0FFF_FFFC, 8'd0, 100, 0);                       // top of the 256 MiB region
    rd(32'h0000_0010, 8'd7, 30, 0);                        // slow master
    // ---- V1: writes ----------------------------------------------------------------------------------------
    wr1(32'h0000_0010, 32'h1234_5678, 4'hF);
    rd(32'h0000_0010, 0, 100, 0);                          // ROM: unchanged / SRAM: new value
    for (int be = 0; be < 16; be++) begin
      wr1(32'h0000_0020, 32'hFEDC_BA98 ^ (32'(be) * 32'h0101_0101), 4'(be));
      rd(32'h0000_0020, 0, 100, 0);
    end
    wr1(32'(4 * (WORDS - 1)), 32'hCAFE_0001, 4'hF);        // last word
    rd(32'(4 * (WORDS - 1)), 0, 100, 0);
    wr1(32'(4 * WORDS), 32'hBAD0_BAD0, 4'hF);              // out of range -> SLVERR, no effect
    rd(32'h0000_0000, 8'd15, 100, 0);
    // burst writes (INCR, per-beat strobes)
    for (int i = 0; i < 8; i++) begin wd[i] = 32'hB000_0000 + 32'(i); ws[i] = 4'hF; end
    wr(32'h0000_0080, 8, 100, 0, 0, 0);
    rd(32'h0000_0080, 8'd7, 100, 0);
    for (int i = 0; i < 4; i++) begin wd[i] = 32'hC000_0000 + 32'(i) * 32'h0101_0101; ws[i] = 4'(1 << i); end
    wr(32'h0000_00A0, 4, 40, 40, 0, 0);
    rd(32'h0000_00A0, 8'd3, 100, 0);
    for (int i = 0; i < 4; i++) begin wd[i] = 32'hD000_0000 + 32'(i); ws[i] = 4'hF; end
    wr(32'(4 * (WORDS - 2)), 4, 100, 0, 0, 0);            // burst write running off the end -> SLVERR
    rd(32'(4 * (WORDS - 4)), 8'd3, 100, 0);
    // write delayed AW, response back-pressure
    wd[0] = 32'h5555_AAAA; ws[0] = 4'hF; wr(32'h0000_0030, 1, 20, 50, 5, 0);
    rd(32'h0000_0030, 0, 100, 0);
    // back-to-back write/read/write
    wr1(32'h0000_0040, 32'h0BAD_F00D, 4'hF); rd(32'h0000_0040, 0, 100, 0); wr1(32'h0000_0044, 32'h1BAD_F00D, 4'hF); rd(32'h0000_0040, 8'd1, 100, 0);
    // simultaneous AR + AW: read first, write afterwards
    @(negedge clk); s_req.arvalid = 1; s_req.araddr = 32'h0000_0048 | BASE; s_req.arlen = 0;
    s_req.awvalid = 1; s_req.awaddr = 32'h0000_004C | BASE; s_req.awlen = 0; s_req.wvalid = 1; s_req.wdata = 32'h7E57_0001; s_req.wstrb = 4'hF; s_req.wlast = 1;
    #1; if (!IS_ROM) chk("read_priority_no_awready", 0, {63'd0, s_rsp.awready});
    @(posedge clk); @(negedge clk); s_req.arvalid = 0; s_req.rready = 1;
    repeat (2) @(negedge clk); s_req.rready = 0;
    begin int g = 0; while (!s_rsp.awready && g < 30) begin @(negedge clk); #1; g++; end end
    @(posedge clk); @(negedge clk); s_req.awvalid = 0;
    begin int g = 0; while (!s_rsp.wready && g < 30) begin @(negedge clk); #1; g++; end end
    @(posedge clk); @(negedge clk); s_req.wvalid = 0; s_req.wlast = 0; s_req.bready = 1;
    begin int g = 0; while (!s_rsp.bvalid && g < 30) begin @(negedge clk); g++; end end
    @(negedge clk); s_req.bready = 0;
    if (!IS_ROM) rm[(32'h0000_004C >> 2)] = 32'h7E57_0001;
    repeat (3) @(negedge clk);
    rd(32'h0000_004C, 0, 100, 0);
    // reset in the middle of a read burst
    @(negedge clk); s_req.arvalid = 1; s_req.araddr = 32'h0000_0000 | BASE; s_req.arlen = 8'd15;
    @(negedge clk); s_req.arvalid = 0; repeat (2) @(negedge clk);
    rst_n = 0; @(negedge clk); @(negedge clk); rst_n = 1; @(negedge clk); #1;
    chk("idle_after_reset", 0, {62'd0, s_rsp.rvalid, s_rsp.bvalid});
    // SRAM has no reset on the array: reference already matches; ROM constant
    rd(32'h0000_0000, 8'd3, 100, 0);

    // ---- V2/V5: 110 randomized transactions ---------------------------------------------------------------------------
    for (int i = 0; i < 110; i++) begin
      logic [31:0] a;
      int nb;
      int rr = ($urandom_range(0, 1)) ? 100 : $urandom_range(20, 90);
      a = 32'($urandom_range(0, WORDS + 8) * 4);
      if ($urandom_range(0, 1)) rd(a, 8'($urandom_range(0, 15)), rr, 1);
      else begin
        nb = $urandom_range(1, 8);
        for (int k = 0; k < nb; k++) begin wd[k] = $urandom(); ws[k] = ($urandom_range(0, 2) == 0) ? 4'($urandom_range(0, 15)) : 4'hF; end
        wr(a, nb, rr, ($urandom_range(0, 2) == 0) ? 40 : 0, $urandom_range(0, 3), 1);
      end
    end
    // final full-array readback against the reference
    for (int i = 0; i < WORDS; i += 8) rd(32'(i * 4), 8'd7, 100, 0);

    finish_report();
    $finish;
  end
endmodule
